---
apiVersion: v1
kind: Namespace
metadata:
  name: java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: java
  name: deployment-java
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-java
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-java
    spec:
      containers:
      - image: public.ecr.aws/r1f4w1h4/springboot-chat-app:latest
        imagePullPolicy: Always
        name: app-2048
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: app-java
  name: service-java
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: app-java
---
